pluginManagement {
	repositories {
		gradlePluginPortal()
		mavenCentral()
	}
}

dependencyResolutionManagement {
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	repositories {
		mavenCentral()
	}
}

rootProject.name = 'payment-platform'
include 'payment-validation-service'
include 'payment-processing-service'
include 'stripe-provider-service'
include 'paypal-provider-service'
